/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
          "primary-fixed": "#e9ddff",
          "primary": "#8b5cf6",
          "surface-container-low": "#131b2e",
          "outline-variant": "#494454",
          "secondary-fixed-dim": "#89ceff",
          "tertiary-fixed": "#ffd8e7",
          "surface-variant": "#1e2638",
          "on-primary-fixed-variant": "#5516be",
          "outline": "#958ea0",
          "secondary-fixed": "#c9e6ff",
          "on-secondary-container": "#00344e",
          "tertiary": "#ffafd3",
          "error-container": "#93000a",
          "on-primary": "#ffffff",
          "surface-container": "#171f33",
          "on-error": "#690005",
          "background": "#0b1326",
          "surface-bright": "#31394d",
          "surface-container-high": "#222a3d",
          "surface": "#0b1326",
          "on-primary-container": "#340080",
          "on-secondary": "#00344d",
          "surface-dim": "#0b1326",
          "on-error-container": "#ffdad6",
          "inverse-primary": "#6d3bd7",
          "tertiary-fixed-dim": "#ffafd3",
          "surface-tint": "#8b5cf6",
          "surface-container-lowest": "#060e20",
          "on-tertiary-container": "#560038",
          "on-primary-fixed": "#23005c",
          "inverse-on-surface": "#283044",
          "secondary-container": "#00a2e6",
          "on-surface": "#dae2fd",
          "tertiary-container": "#e364a7",
          "on-tertiary-fixed": "#3d0026",
          "on-tertiary-fixed-variant": "#85145a",
          "on-background": "#dae2fd",
          "primary-fixed-dim": "#8b5cf6",
          "surface-container-highest": "#2d3449",
          "on-tertiary": "#620040",
          "secondary": "#a78bfa",
          "on-surface-variant": "#94a3b8",
          "inverse-surface": "#dae2fd",
          "error": "#ffb4ab",
          "on-secondary-fixed-variant": "#004c6e",
          "on-secondary-fixed": "#001e2f",
          "primary-container": "#7c3aed"
      },
      "borderRadius": {
          "DEFAULT": "0.5rem",
          "lg": "0.75rem",
          "xl": "1rem",
          "2xl": "1.5rem",
          "full": "9999px"
      },
      "spacing": {
          "bento-gap": "24px",
          "unit": "8px",
          "container-max": "1440px",
          "margin": "40px",
          "gutter": "32px"
      },
      "fontFamily": {
          "body-md": ["Geist", "sans-serif"],
          "body-lg": ["Geist", "sans-serif"],
          "headline-lg": ["Sora", "sans-serif"],
          "display-lg": ["Sora", "sans-serif"],
          "label-caps": ["JetBrains Mono", "monospace"],
          "headline-md": ["Sora", "sans-serif"],
          "stat-value": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
          "body-md": ["14px", {"lineHeight": "22px", "fontWeight": "400"}],
          "body-lg": ["16px", {"lineHeight": "26px", "fontWeight": "400"}],
          "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.15em", "fontWeight": "600"}],
          "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
          "stat-value": ["24px", {"lineHeight": "1", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
